
name: JDConf Demo CI

on:
  push:
    branches:
      - main
    # paths:
    #   - 'pom.xml'
    #   - 'src/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build, Test, and Deploy
        run: mvn clean deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
